models:
  clip: "openai/clip-vit-base-patch32"
  yolo: "yolov8x.pt"
  traffic_signs: "yolov8n.pt"

processing:
  sample_rate: 1
  max_workers: 4
  confidence_threshold: 0.5

api:
  host: "0.0.0.0"
  port: 8001
  debug: false
api:
  host: localhost
  port: 8001
  debug: false

frontend:
  port: 8501
  title: "Video Analytics Dashboard"
  
backend:
  port: 8502
  workers: 4

logging:
  level: INFO
  file: video_analytics.log

services:
  openai:
    model: gpt-4-vision-preview-v2
    max_tokens: 500
  
  detection:
    model: yolov8n.pt
    confidence: 0.25
    sample_rate: 30
