# DXV Video Analytics Configuration
api:
  debug: true
  port: 8000
  cors_origins: "*"
  rate_limits:
    default: "1000 per day"
    uploads: "100 per hour"
    files_list: "200 per hour"
  branding:
    name: "DXV"
    description: "Deep Experience Vision"

websocket:
  port: 8000
  ssl_enabled: false
  ping_timeout: 60
  ping_interval: 25
  max_buffer_size: 104857600  # 100MB
  reconnection:
    attempts: 10
    delay: 1000
    max_delay: 5000

logging:
  level: "INFO"
  file: "video_analytics.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

frontend:
  build_path: "../frontend/build"
  branding:
    logo: "assets/logo.png"
    favicon: "assets/favicon.png"
    primary_color: "#bd9544"  # Gold from logo
    secondary_color: "#808080" # Gray from logo

content_storage:
  base_path: "tmp_content"
  max_file_size: 104857600  # 100MB
  allowed_extensions:
    - ".mp4"
    - ".avi"
    - ".mov"
    - ".webm"
  cleanup_interval: 86400  # 24 hours
  max_age: 604800  # 7 days

video:
  max_frame_rate: 30
  default_resolution:
    width: 1280
    height: 720
  compression:
    quality: 85
    format: "jpeg"

analysis:
  edge_detection:
    enabled: true
    low_threshold: 100
    high_threshold: 200
  motion_detection:
    enabled: true
    sensitivity: 20
    min_area: 500
  object_detection:
    enabled: true
    confidence_threshold: 0.5
    nms_threshold: 0.4

storage:
  base_path: "tmp_content"
  subdirs:
    - "uploads"
    - "analysis"
    - "chat_history"
    - "visualizations"
    - "knowledgebase"
